"""Predefined parameter sets for the Higgs propagator calculation."""

import numpy as np

PRESETS = {
    "default": {
        "name": "Default (Reuter NGFP)",
        "description": "Standard parameters from Falls-Litim 2014",
        "theta_r": 2.714,
        "theta_i": 2.396,
        "N_max": 39.34,
        "rtol": 1e-8,
        "atol": 1e-10,
        "termination": "fixed",
        "A_G": 0.05,
        "A_lambda": 0.03,
    },
    "resonance": {
        "name": "Resonance Termination",
        "description": "N_max = 30pi/theta_i for exact winding number",
        "theta_r": 2.714,
        "theta_i": 2.396,
        "N_max": 30.0 * np.pi / 2.396,
        "rtol": 1e-8,
        "atol": 1e-10,
        "termination": "resonance",
        "A_G": 0.05,
        "A_lambda": 0.03,
    },
    "high_precision": {
        "name": "High Precision",
        "description": "Tighter tolerances for research-grade results",
        "theta_r": 2.714,
        "theta_i": 2.396,
        "N_max": 39.34,
        "rtol": 1e-10,
        "atol": 1e-12,
        "termination": "fixed",
        "A_G": 0.05,
        "A_lambda": 0.03,
    },
    "fast_preview": {
        "name": "Fast Preview",
        "description": "Loose tolerances for quick parameter exploration",
        "theta_r": 2.714,
        "theta_i": 2.396,
        "N_max": 39.34,
        "rtol": 1e-6,
        "atol": 1e-8,
        "termination": "fixed",
        "A_G": 0.05,
        "A_lambda": 0.03,
    },
    "shaposhnikov_wetterich": {
        "name": "Shaposhnikov-Wetterich",
        "description": "Parameters matching SW 2010 scenario (lambda(M_Pl)=0)",
        "theta_r": 2.714,
        "theta_i": 2.396,
        "N_max": 39.34,
        "rtol": 1e-8,
        "atol": 1e-10,
        "termination": "fixed",
        "A_G": 0.05,
        "A_lambda": 0.03,
    },
}
